var json = `[
  {
    "id": 72988541,
    "name": "workshop-cms",
    "full_name": "emilyb7/workshop-cms",
    "owner": {
      "login": "emilyb7",
      "id": 17532458,
      "avatar_url": "https://avatars.githubusercontent.com/u/17532458?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/emilyb7",
      "html_url": "https://github.com/emilyb7",
      "followers_url": "https://api.github.com/users/emilyb7/followers",
      "following_url": "https://api.github.com/users/emilyb7/following{/other_user}",
      "gists_url": "https://api.github.com/users/emilyb7/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/emilyb7/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/emilyb7/subscriptions",
      "organizations_url": "https://api.github.com/users/emilyb7/orgs",
      "repos_url": "https://api.github.com/users/emilyb7/repos",
      "events_url": "https://api.github.com/users/emilyb7/events{/privacy}",
      "received_events_url": "https://api.github.com/users/emilyb7/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/emilyb7/workshop-cms",
    "description": "CMS workshop for February 2016 Node Girls workshop ",
    "fork": true,
    "url": "https://api.github.com/repos/emilyb7/workshop-cms",
    "forks_url": "https://api.github.com/repos/emilyb7/workshop-cms/forks",
    "keys_url": "https://api.github.com/repos/emilyb7/workshop-cms/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/emilyb7/workshop-cms/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/emilyb7/workshop-cms/teams",
    "hooks_url": "https://api.github.com/repos/emilyb7/workshop-cms/hooks",
    "issue_events_url": "https://api.github.com/repos/emilyb7/workshop-cms/issues/events{/number}",
    "events_url": "https://api.github.com/repos/emilyb7/workshop-cms/events",
    "assignees_url": "https://api.github.com/repos/emilyb7/workshop-cms/assignees{/user}",
    "branches_url": "https://api.github.com/repos/emilyb7/workshop-cms/branches{/branch}",
    "tags_url": "https://api.github.com/repos/emilyb7/workshop-cms/tags",
    "blobs_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/emilyb7/workshop-cms/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/emilyb7/workshop-cms/languages",
    "stargazers_url": "https://api.github.com/repos/emilyb7/workshop-cms/stargazers",
    "contributors_url": "https://api.github.com/repos/emilyb7/workshop-cms/contributors",
    "subscribers_url": "https://api.github.com/repos/emilyb7/workshop-cms/subscribers",
    "subscription_url": "https://api.github.com/repos/emilyb7/workshop-cms/subscription",
    "commits_url": "https://api.github.com/repos/emilyb7/workshop-cms/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/emilyb7/workshop-cms/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/emilyb7/workshop-cms/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/emilyb7/workshop-cms/contents/{+path}",
    "compare_url": "https://api.github.com/repos/emilyb7/workshop-cms/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/emilyb7/workshop-cms/merges",
    "archive_url": "https://api.github.com/repos/emilyb7/workshop-cms/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/emilyb7/workshop-cms/downloads",
    "issues_url": "https://api.github.com/repos/emilyb7/workshop-cms/issues{/number}",
    "pulls_url": "https://api.github.com/repos/emilyb7/workshop-cms/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/emilyb7/workshop-cms/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/emilyb7/workshop-cms/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/emilyb7/workshop-cms/labels{/name}",
    "releases_url": "https://api.github.com/repos/emilyb7/workshop-cms/releases{/id}",
    "deployments_url": "https://api.github.com/repos/emilyb7/workshop-cms/deployments",
    "created_at": "2016-11-06T12:17:09Z",
    "updated_at": "2016-08-04T04:13:56Z",
    "pushed_at": "2016-11-06T19:09:10Z",
    "git_url": "git://github.com/emilyb7/workshop-cms.git",
    "ssh_url": "git@github.com:emilyb7/workshop-cms.git",
    "clone_url": "https://github.com/emilyb7/workshop-cms.git",
    "svn_url": "https://github.com/emilyb7/workshop-cms",
    "homepage": null,
    "size": 685,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 72988541,
    "name": "workshop-cms",
    "full_name": "emilyb7/workshop-cms",
    "owner": {
      "login": "emilyb7",
      "id": 17532458,
      "avatar_url": "https://avatars.githubusercontent.com/u/17532458?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/emilyb7",
      "html_url": "https://github.com/emilyb7",
      "followers_url": "https://api.github.com/users/emilyb7/followers",
      "following_url": "https://api.github.com/users/emilyb7/following{/other_user}",
      "gists_url": "https://api.github.com/users/emilyb7/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/emilyb7/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/emilyb7/subscriptions",
      "organizations_url": "https://api.github.com/users/emilyb7/orgs",
      "repos_url": "https://api.github.com/users/emilyb7/repos",
      "events_url": "https://api.github.com/users/emilyb7/events{/privacy}",
      "received_events_url": "https://api.github.com/users/emilyb7/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/emilyb7/workshop-cms",
    "description": "CMS workshop for February 2016 Node Girls workshop ",
    "fork": true,
    "url": "https://api.github.com/repos/emilyb7/workshop-cms",
    "forks_url": "https://api.github.com/repos/emilyb7/workshop-cms/forks",
    "keys_url": "https://api.github.com/repos/emilyb7/workshop-cms/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/emilyb7/workshop-cms/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/emilyb7/workshop-cms/teams",
    "hooks_url": "https://api.github.com/repos/emilyb7/workshop-cms/hooks",
    "issue_events_url": "https://api.github.com/repos/emilyb7/workshop-cms/issues/events{/number}",
    "events_url": "https://api.github.com/repos/emilyb7/workshop-cms/events",
    "assignees_url": "https://api.github.com/repos/emilyb7/workshop-cms/assignees{/user}",
    "branches_url": "https://api.github.com/repos/emilyb7/workshop-cms/branches{/branch}",
    "tags_url": "https://api.github.com/repos/emilyb7/workshop-cms/tags",
    "blobs_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/emilyb7/workshop-cms/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/emilyb7/workshop-cms/languages",
    "stargazers_url": "https://api.github.com/repos/emilyb7/workshop-cms/stargazers",
    "contributors_url": "https://api.github.com/repos/emilyb7/workshop-cms/contributors",
    "subscribers_url": "https://api.github.com/repos/emilyb7/workshop-cms/subscribers",
    "subscription_url": "https://api.github.com/repos/emilyb7/workshop-cms/subscription",
    "commits_url": "https://api.github.com/repos/emilyb7/workshop-cms/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/emilyb7/workshop-cms/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/emilyb7/workshop-cms/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/emilyb7/workshop-cms/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/emilyb7/workshop-cms/contents/{+path}",
    "compare_url": "https://api.github.com/repos/emilyb7/workshop-cms/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/emilyb7/workshop-cms/merges",
    "archive_url": "https://api.github.com/repos/emilyb7/workshop-cms/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/emilyb7/workshop-cms/downloads",
    "issues_url": "https://api.github.com/repos/emilyb7/workshop-cms/issues{/number}",
    "pulls_url": "https://api.github.com/repos/emilyb7/workshop-cms/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/emilyb7/workshop-cms/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/emilyb7/workshop-cms/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/emilyb7/workshop-cms/labels{/name}",
    "releases_url": "https://api.github.com/repos/emilyb7/workshop-cms/releases{/id}",
    "deployments_url": "https://api.github.com/repos/emilyb7/workshop-cms/deployments",
    "created_at": "2016-11-06T12:17:09Z",
    "updated_at": "2016-08-04T04:13:56Z",
    "pushed_at": "2016-11-06T19:09:10Z",
    "git_url": "git://github.com/emilyb7/workshop-cms.git",
    "ssh_url": "git@github.com:emilyb7/workshop-cms.git",
    "clone_url": "https://github.com/emilyb7/workshop-cms.git",
    "svn_url": "https://github.com/emilyb7/workshop-cms",
    "homepage": null,
    "size": 685,
    "stargazers_count": 3,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }]`;

QUnit.test( "hello test", function( assert ) {
  assert.ok( 1 == "1", "Passed!" );
});

QUnit.test("getLanguages returns an array of languages with no duplicates", function (assert) {
  assert.deepEqual(getLanguages(JSON.parse(json).sort()), ["JavaScript", "HTML"].sort());
})

QUnit.test("countStars returns an integer representing the total number of stars for all repos", function (assert) {
  assert.equal(countStars(JSON.parse(json)), 3);
})
